# Generated by Django 4.2 on 2025-09-20 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=10)),
                ('place', models.CharField(blank=True, max_length=255)),
                ('external_id', models.CharField(blank=True, help_text='Optional external identifier (device/patient id)', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm', models.PositiveSmallIntegerField()),
                ('recorded_at', models.DateTimeField()),
                ('device_id', models.CharField(blank=True, max_length=128, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Optional additional data from device', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_rates', to='patients.patient')),
            ],
            options={
                'ordering': ('-recorded_at',),
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['external_id'], name='patients_pa_externa_261412_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['owner'], name='patients_pa_owner_i_b098c8_idx'),
        ),
        migrations.AddIndex(
            model_name='heartrate',
            index=models.Index(fields=['patient', 'recorded_at'], name='patients_he_patient_a73817_idx'),
        ),
        migrations.AddIndex(
            model_name='heartrate',
            index=models.Index(fields=['recorded_at'], name='patients_he_recorde_d3f6ce_idx'),
        ),
    ]
