name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Run lint
        run: |
          flake8 --max-line-length=100 .

      - name: Run migrations and tests
        run: |
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput
          python manage.py test --verbosity=2
